### PR TITLE
Fix write-after-free in Pipewire stream cleanup

### LINKED ISSUE #2864: Niri crash on Pipewire video stream disconnect
Niri always crashes when trying to share or record my screen via Pipewire. Some programs crash my session immediately, others only when their stream disconnects. OBS Studio, for instance, crashes Niri right after I close it. Once I tried screensharing in the Signal flatpak app, crashed immediately.

Here are my Niri logs I grabbed right after it crashed from OBS Studio:
```
Nov 21 14:00:05 T480 systemd[2943]: Starting niri.service - A scrollable-tiling Wayland compositor...
Nov 21 14:00:06 T480 niri[3317]: 2025-11-21T13:00:06.046516Z  INFO niri: starting version 25.08
Nov 21 14:00:06 T480 niri[3317]: 2025-11-21T13:00:06.114835Z DEBUG niri_config: loaded config from "/home/mikolaj/.config/niri/config.kdl"
Nov 21 14:00:06 T480 niri[3317]: 2025-11-21T13:00:06.323089Z  INFO niri::backend::tty: using as the render node: "/dev/dri/renderD128"
Nov 21 14:00:06 T480 niri[3317]: 2025-11-21T13:00:06.561865Z DEBUG niri::backend::tty: device added: 57857 "/dev/dri/card1"
Nov 21 14:00:06 T480 niri[3317]: 2025-11-21T13:00:06.894189Z DEBUG niri::backend::tty: this is the primary node
Nov 21 14:00:06 T480 niri[3317]: 2025-11-21T13:00:06.894204Z DEBUG niri::backend::tty: this is the primary render node
Nov 21 14:00:06 T480 niri[3317]: 2025-11-21T13:00:06.933175Z  WARN niri::backend::tty: error binding wl-display in EGL: EglExtensionNotSupported(["EGL_WL_bind_wayland_display"])
Nov 21 14:00:06 T480 niri[3317]: 2025-11-21T13:00:06.970649Z DEBUG niri::backend::tty: device changed: 57857
Nov 21 14:00:07 T480 niri[3317]: 2025-11-21T13:00:07.695590Z DEBUG niri::backend::tty: new connector: eDP-1 "AU Optronics 0x2336 Unknown"
Nov 21 14:00:07 T480 niri[3317]: 2025-11-21T13:00:07.695693Z DEBUG niri::backend::tty: connecting connector: eDP-1
Nov 21 14:00:07 T480 niri[3317]: 2025-11-21T13:00:07.695771Z DEBUG niri::backend::tty: picking mode: Mode { name: "2560x1440", clock: 245500, size: (2560, 1440), hsync: (2608, 2640, 2720), vsync: (1443, 1448, 1504), hskew: 0, vscan: 0, vrefresh: 60, mode_type: ModeTypeFlags(PREFERRED | DRIVER) }
Nov 21 14:00:07 T480 niri[3317]: 2025-11-21T13:00:07.695995Z DEBUG niri::backend::tty: error resetting HDR properties: couldn't find property: "HDR_OUTPUT_METADATA"
Nov 21 14:00:07 T480 niri[3317]: 2025-11-21T13:00:07.699112Z  WARN niri::backend::tty: cannot enable VRR because connector does not support it
Nov 21 14:00:07 T480 niri[3317]: 2025-11-21T13:00:07.708169Z DEBUG niri::niri: putting output eDP-1 at x=0 y=0
Nov 21 14:00:07 T480 niri[3317]: 2025-11-21T13:00:07.708372Z  INFO niri: listening on Wayland socket: wayland-1
Nov 21 14:00:07 T480 niri[3317]: 2025-11-21T13:00:07.708397Z  INFO niri: IPC listening on: /run/user/1000/niri.wayland-1.3317.sock
Nov 21 14:00:07 T480 niri[3317]: 2025-11-21T13:00:07.743570Z  INFO niri: listening on X11 socket: :0
Nov 21 14:00:07 T480 systemd[2943]: Started niri.service - A scrollable-tiling Wayland compositor.
Nov 21 14:00:27 T480 niri[3317]: 2025-11-21T13:00:27.546700Z DEBUG niri::utils::xwayland::satellite: connection to X11 abstract socket; spawning xwayland-satellite
Nov 21 16:06:51 T480 niri[3317]: 2025-11-21T15:06:51.306890Z  INFO niri::niri: locking session
Nov 21 16:06:51 T480 niri[3317]: 2025-11-21T15:06:51.376300Z  INFO niri::niri: refusing lock as another client is currently locking
Nov 21 17:11:24 T480 niri[3317]: 2025-11-21T16:11:24.854308Z  INFO niri::niri: unlocking session
Nov 21 17:12:03 T480 niri[3317]: 2025-11-21T16:12:03.330789Z  WARN niri::utils::xwayland::satellite: xwayland-satellite exited with: exit status: 101
Nov 21 17:12:15 T480 niri[3317]: 2025-11-21T16:12:15.206400Z DEBUG niri::utils::xwayland::satellite: connection to X11 abstract socket; spawning xwayland-satellite
Nov 21 17:12:32 T480 niri[3317]: 2025-11-21T16:12:32.679456Z  WARN niri::utils::xwayland::satellite: xwayland-satellite exited with: exit status: 101
Nov 21 17:12:35 T480 niri[3317]: 2025-11-21T16:12:35.872650Z DEBUG niri::utils::xwayland::satellite: connection to X11 abstract socket; spawning xwayland-satellite
Nov 21 17:13:09 T480 niri[3317]: libinput error: event5  - Keychron Keychron C2 Pro: client bug: event processing lagging behind by 25ms, your system is too slow
Nov 21 17:13:10 T480 niri[3317]: libinput error: event5  - Keychron Keychron C2 Pro: client bug: event processing lagging behind by 22ms, your system is too slow
Nov 21 17:13:10 T480 niri[3317]: libinput error: event5  - Keychron Keychron C2 Pro: client bug: event processing lagging behind by 22ms, your system is too slow
Nov 21 17:13:11 T480 niri[3317]: libinput error: event5  - Keychron Keychron C2 Pro: client bug: event processing lagging behind by 24ms, your system is too slow
Nov 21 17:13:13 T480 niri[3317]: libinput error: event5  - Keychron Keychron C2 Pro: client bug: event processing lagging behind by 30ms, your system is too slow
Nov 21 17:13:13 T480 niri[3317]: libinput error: event5  - Keychron Keychron C2 Pro: WARNING: log rate limit exceeded (5 msgs per 60min). Discarding future messages.
Nov 21 17:14:10 T480 niri[3317]: 2025-11-21T16:14:10.137392Z DEBUG niri_config: loaded config from "/home/mikolaj/.config/niri/config.kdl"
Nov 21 17:14:31 T480 niri[3317]: 2025-11-21T16:14:31.686050Z DEBUG niri_config: loaded config from "/home/mikolaj/.config/niri/config.kdl"
Nov 21 17:14:58 T480 niri[3317]: 2025-11-21T16:14:58.234055Z  WARN niri::utils::xwayland::satellite: xwayland-satellite exited with: exit status: 101
Nov 21 17:15:01 T480 niri[3317]: 2025-11-21T16:15:01.676036Z DEBUG niri::utils::xwayland::satellite: connection to X11 abstract socket; spawning xwayland-satellite
Nov 21 17:19:59 T480 niri[3317]: 2025-11-21T16:19:59.517660Z  WARN niri::utils::xwayland::satellite: xwayland-satellite exited with: exit status: 101
Nov 21 17:20:02 T480 niri[3317]: 2025-11-21T16:20:02.948711Z DEBUG niri::utils::xwayland::satellite: connection to X11 abstract socket; spawning xwayland-satellite
Nov 21 18:05:35 T480 niri[3317]: 2025-11-21T17:05:35.266711Z DEBUG niri::dbus::mutter_screen_cast: record_monitor connector="eDP-1" properties=RecordMonitorProperties { cursor_mode: Some(Metadata), _is_recording: None }
Nov 21 18:05:35 T480 niri[3317]: 2025-11-21T17:05:35.268913Z DEBUG niri::dbus::mutter_screen_cast: start
Nov 21 18:05:35 T480 niri[3317]: 2025-11-21T17:05:35.273136Z DEBUG niri::niri: StartCast session_id=0 stream_id=0
Nov 21 18:05:35 T480 niri[3317]: 2025-11-21T17:05:35.278832Z DEBUG niri::pw_utils: pw stream: state changed: Unconnected -> Connecting stream_id=0
Nov 21 18:05:35 T480 niri[3317]: 2025-11-21T17:05:35.286731Z DEBUG niri::pw_utils: pw stream: state changed: Connecting -> Paused stream_id=0
Nov 21 18:05:35 T480 niri[3317]: 2025-11-21T17:05:35.286782Z DEBUG niri::pw_utils: pw stream: sending signal with 85 stream_id=0
Nov 21 18:05:35 T480 niri[3317]: 2025-11-21T17:05:35.352241Z DEBUG niri::pw_utils: pw stream: got format = VideoInfoRaw { format: VideoFormat::BGRx, flags: VideoFlags(0xc), modifier: 0, size: spa_rectangle { width: 2560, height: 1440 }, framerate: spa_fraction { num: 0, denom: 1 }, max_framerate: spa_fraction { num: 60012, denom: 1000 }, views: 0, interlace_mode: 0, pixel_aspect_ratio: spa_fraction { num: 0, denom: 0 }, multiview_mode: 0, multiview_flags: 0, chroma_site: 0, color_range: 0, color_matrix: 0, transfer_function: 0, color_primaries: 0 } stream_id=0
Nov 21 18:05:35 T480 niri[3317]: 2025-11-21T17:05:35.352288Z DEBUG niri::pw_utils: pw stream: fixating the modifier stream_id=0
Nov 21 18:05:35 T480 niri[3317]: 2025-11-21T17:05:35.352299Z DEBUG niri::pw_utils: find_preferred_modifier: size=Size<smithay::utils::geometry::Physical> { w: 2560, h: 1440 }, fourcc=XR24, modifiers=[0, 72057594037927937, 72057594037927938, 72057594037927940, 72057594037927935]
Nov 21 18:05:35 T480 niri[3317]: 2025-11-21T17:05:35.354519Z DEBUG niri::pw_utils: pw stream: allocation successful (modifier=I915_y_tiled_ccs, plane_count=2), moving to confirmation pending stream_id=0
Nov 21 18:05:35 T480 niri[3317]: 2025-11-21T17:05:35.355003Z DEBUG niri::pw_utils: pw stream: got format = VideoInfoRaw { format: VideoFormat::BGRx, flags: VideoFlags(0x4), modifier: 72057594037927940, size: spa_rectangle { width: 2560, height: 1440 }, framerate: spa_fraction { num: 0, denom: 1 }, max_framerate: spa_fraction { num: 60012, denom: 1000 }, views: 0, interlace_mode: 0, pixel_aspect_ratio: spa_fraction { num: 0, denom: 0 }, multiview_mode: 0, multiview_flags: 0, chroma_site: 0, color_range: 0, color_matrix: 0, transfer_function: 0, color_primaries: 0 } stream_id=0
Nov 21 18:05:35 T480 niri[3317]: 2025-11-21T17:05:35.355025Z DEBUG niri::pw_utils: pw stream: moving to ready state stream_id=0
Nov 21 18:05:35 T480 niri[3317]: 2025-11-21T17:05:35.404355Z DEBUG niri::pw_utils: pw stream: state changed: Paused -> Streaming stream_id=0
Nov 21 18:05:43 T480 niri[3317]: 2025-11-21T17:05:43.226257Z DEBUG niri::pw_utils: pw stream: state changed: Streaming -> Paused stream_id=0
Nov 21 18:05:43 T480 niri[3317]: 2025-11-21T17:05:43.300175Z DEBUG niri::dbus::mutter_screen_cast: stop
Nov 21 18:05:43 T480 niri[3317]: 2025-11-21T17:05:43.348874Z DEBUG niri::niri: StopCast session_id=0
Nov 21 18:05:43 T480 niri[3317]: 2025-11-21T17:05:43.348961Z DEBUG niri::pw_utils: pw stream: state changed: Paused -> Unconnected stream_id=0
Nov 21 18:05:44 T480 niri[3317]: fatal allocator error: detected write after free
Nov 21 18:05:44 T480 systemd[2943]: niri.service: Main process exited, code=dumped, status=6/ABRT
Nov 21 18:05:45 T480 systemd[2943]: niri.service: Failed with result 'core-dump'.
Nov 21 18:05:45 T480 systemd[2943]: niri.service: Consumed 25min 55.189s CPU time, 717.5M memory peak.
```

> fatal allocator error: detected write after free

Didn't expect that from a Rust - powered compositor. Maybe it's another memory-unsafe component that is causing this, though?

This memory corruption bug is likely exposed because my OS preloads [`hardened_malloc`](https://github.com/GrapheneOS/hardened_malloc) system-wide. Note that `hardened_malloc` is not causing the memory bug, but rather exposing it as I mentioned.

Dunno if that helps, but recording my screen on GNOME, which as far as I understand, uses the same backed for this function, does not crash my session.

If some things are unclear, or if more info is needed, I'll be glad to help!

### My Niri config
https://github.com/tpaau/dots/commit/9424af94b0337d7bb7235f42553dd19e0e733532#diff-adc67e167f5fd613704fd180d94118c7d643db4dd6b26d10088daa510fa9a2de

### System Information

* niri version: niri 25.08

* Distro: secureblue 43.20251121.0

* GPU: Intel UHD 620

* CPU: Intel Core i7-8650U

### PR DESCRIPTION
**Pull request by kriive**
# Description
This fixes a crash observed when stopping a screen cast, confirmed by [ASan output](https://github.com/user-attachments/files/24471855/asan.txt).

Fixes #2864.

The `Cast` struct in [src/pw_utils.rs]() dropped the `stream` field (owning the PipeWire stream) before the `_listener` field (`StreamListener`). The `StreamListener` destructor attempts to unregister itself from the stream. Since fields are dropped in declaration order, the stream was destroyed first, causing `StreamListener::drop` to access freed memory.

# Fix
We reordered the fields in the `Cast` struct so `_listener` is declared before `stream`. This ensures the listener is dropped and unregistered while the stream is still valid.

### CODE REVIEW

File: src/pw_utils.rs [hunk 1]
```diff
@@ -72,8 +72,8 @@ pub struct Cast {
     event_loop: LoopHandle<'static, State>,
     pub session_id: usize,
     pub stream_id: usize,
-    pub stream: StreamRc,
     _listener: StreamListener<()>,
```
Comment (YaLTeR) [inline src/pw_utils.rs:76]:
```suggestion
    // Listener is dropped before Stream to prevent a use-after-free.
    _listener: StreamListener<()>,
```

**Comment by YaLTeR** [comment]
Thanks
